//! Wire protocol between `lixund` and the `lixun-semantic-worker`
//! sidecar.
//!
//! ## Frame format
//!
//! Mirrors the framing used by `lixun-ipc`:
//!
//! ```text
//! +-------------------+--------------------+--------------------+
//! | u32 BE total_len  | u16 BE proto_ver   | JSON payload       |
//! |   (= 2 + len(JSON)) |   = PROTOCOL_VERSION | (UTF-8, no LF)  |
//! +-------------------+--------------------+--------------------+
//! ```
//!
//! `total_len` covers the version field plus the JSON body but does
//! not include itself. Receivers that see a version outside
//! `MIN_PROTOCOL_VERSION..=PROTOCOL_VERSION` close the connection.
//!
//! ## Direction
//!
//! Two parties talk in both directions on a single Unix socket:
//!
//! - The **daemon** sends [`Cmd`] (commands the worker must execute)
//!   and receives [`Msg`] (worker-initiated messages, including RPC
//!   responses and DocStore callbacks).
//! - The **worker** sends [`Msg`] and receives [`Cmd`].
//!
//! Each side uses a [`FrameCodec<I, O>`] parameterised by what it
//! decodes (`I`) and what it encodes (`O`). The two sides mirror each
//! other:
//!
//! | side    | reads (`I`) | writes (`O`)     |
//! |---------|-------------|------------------|
//! | daemon  | [`Msg`]     | [`Cmd`]          |
//! | worker  | [`Cmd`]     | [`Msg`]          |
//!
//! ## Request/response correlation
//!
//! Every command that expects a reply carries a `req_id: u64`
//! generated by the sender. The reply [`Msg`] echoes the same
//! `req_id`. Fire-and-forget commands (e.g. [`Cmd::Embed`]) carry
//! `req_id: 0` and never produce a reply on the happy path; failures
//! still surface via [`Msg::Error`] with `req_id: 0`.

use std::marker::PhantomData;

use bytes::{Buf, BufMut, BytesMut};
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use tokio_util::codec::{Decoder, Encoder};

use lixun_core::Hit;
use lixun_mutation::{AnnHit, Modality, UpsertedDoc};

pub const PROTOCOL_VERSION: u16 = 2;
pub const MIN_PROTOCOL_VERSION: u16 = 2;

/// Daemon → worker. Either a fire-and-forget mutation
/// ([`Cmd::Embed`], [`Cmd::Delete`]) or a request expecting a single
/// matching [`Msg`] reply correlated by `req_id`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Cmd {
    /// First frame on a fresh connection. Worker replies with
    /// [`Msg::HandshakeOk`] or closes.
    Handshake { proto_version: u16 },
    /// Fire-and-forget batch enqueue.
    Embed { docs: Vec<UpsertedDoc> },
    /// Fire-and-forget delete.
    Delete { doc_id: String },
    /// ANN search by text query. Worker embeds the query and returns
    /// [`Msg::SearchResult`] with up to `k` hits.
    SearchText { req_id: u64, query: String, k: u32 },
    /// ANN search by image — same shape as [`Cmd::SearchText`] but
    /// routes through the image embedder/channel.
    SearchImage { req_id: u64, query: String, k: u32 },
    /// Anchor-based query modality classification. Worker embeds the
    /// query via CLIP text encoder, computes cosine against pre-embedded
    /// image/text anchors, returns [`Msg::ClassifyResult`].
    ClassifyQuery { req_id: u64, query: String },
    /// Trigger a backfill walk. Worker drives the loop and pulls
    /// missing docs via callback messages
    /// ([`Msg::CallAllDocIds`] etc.). Reply on completion is
    /// [`Msg::BackfillComplete`].
    BackfillStart { req_id: u64 },
    /// Reply to a [`Msg::CallAllDocIds`] / [`Msg::CallHydrateDoc`] /
    /// [`Msg::CallGetBody`] callback. `req_id` matches the callback's
    /// `req_id`.
    CallbackReply { req_id: u64, resp: CallbackResp },
    /// Graceful shutdown — worker should drain pending writes, close
    /// LanceDB, then exit 0.
    Shutdown,
}

/// Worker → daemon. RPC replies, callbacks, async events.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Msg {
    /// Reply to [`Cmd::Handshake`]. `proto_version` is the worker
    /// build's `PROTOCOL_VERSION`; daemon enforces version compat.
    HandshakeOk {
        proto_version: u16,
        worker_version: String,
    },
    /// Reply to [`Cmd::SearchText`] or [`Cmd::SearchImage`].
    SearchResult { req_id: u64, hits: Vec<AnnHit> },
    /// Reply to [`Cmd::ClassifyQuery`].
    ClassifyResult { req_id: u64, modality: Modality },
    /// Worker → daemon DocStore callback: list every indexed doc id.
    CallAllDocIds { req_id: u64 },
    /// Worker → daemon DocStore callback: hydrate one doc by id.
    CallHydrateDoc { req_id: u64, doc_id: String },
    /// Worker → daemon DocStore callback: fetch the stored body of a
    /// doc.
    CallGetBody { req_id: u64, doc_id: String },
    /// Reply to [`Cmd::BackfillStart`] when the walk finishes.
    BackfillComplete {
        req_id: u64,
        submitted: u64,
        total: u64,
    },
    /// Generic failure — `req_id == 0` means the failure was not
    /// tied to a specific outstanding request (e.g. a write batch
    /// failed mid-flush).
    Error {
        req_id: u64,
        code: ErrorCode,
        detail: String,
    },
}

/// Daemon's reply to a worker-initiated DocStore callback.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum CallbackResp {
    AllDocIds {
        ids: Vec<String>,
    },
    /// `hit` is `None` when the doc is gone (race with a delete).
    /// `ScoreBreakdown` from `DocStore::hydrate_doc` is intentionally
    /// not part of this payload: the only consumer (semantic
    /// backfill) does not read it, so keeping it off the wire avoids
    /// adding `serde` derives to `lixun_core::ScoreBreakdown`.
    HydrateDoc {
        hit: Option<Hit>,
    },
    GetBody {
        body: Option<String>,
    },
    Error {
        code: ErrorCode,
        detail: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    /// Wrong/unknown `req_id`, malformed payload past the JSON layer.
    BadRequest,
    /// Embedder failure, store failure, anything the worker classes
    /// as transient.
    Internal,
    /// LanceDB / journal IO failure.
    Storage,
    /// Daemon's DocStore callback returned an error or timed out.
    Callback,
    /// Protocol version mismatch on handshake.
    Version,
}

#[derive(Default)]
enum DecodeState {
    #[default]
    Header,
    Version(usize),
    Payload(usize),
}

/// Length-prefixed JSON codec parameterised by what each side
/// decodes (`I`) and what it encodes (`O`).
pub struct FrameCodec<I, O> {
    state: DecodeState,
    _phantom: PhantomData<fn() -> (I, O)>,
}

impl<I, O> Default for FrameCodec<I, O> {
    fn default() -> Self {
        Self {
            state: DecodeState::Header,
            _phantom: PhantomData,
        }
    }
}

impl<I, O> FrameCodec<I, O> {
    pub fn new() -> Self {
        Self::default()
    }
}

impl<I, O> Encoder<O> for FrameCodec<I, O>
where
    O: Serialize,
{
    type Error = std::io::Error;

    fn encode(&mut self, item: O, dst: &mut BytesMut) -> Result<(), Self::Error> {
        let json = serde_json::to_vec(&item)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
        let total_len = 2 + json.len();
        if total_len > u32::MAX as usize {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                "frame too large",
            ));
        }
        dst.reserve(4 + total_len);
        dst.put_u32(total_len as u32);
        dst.put_u16(PROTOCOL_VERSION);
        dst.put_slice(&json);
        Ok(())
    }
}

impl<I, O> Decoder for FrameCodec<I, O>
where
    I: DeserializeOwned,
{
    type Item = I;
    type Error = std::io::Error;

    fn decode(&mut self, src: &mut BytesMut) -> Result<Option<Self::Item>, Self::Error> {
        loop {
            match self.state {
                DecodeState::Header => {
                    if src.len() < 4 {
                        return Ok(None);
                    }
                    let len = src.get_u32() as usize;
                    if len < 2 {
                        return Err(std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            "frame too short for version",
                        ));
                    }
                    self.state = DecodeState::Version(len);
                }
                DecodeState::Version(len) => {
                    if src.len() < 2 {
                        return Ok(None);
                    }
                    let version = src.get_u16();
                    if !(MIN_PROTOCOL_VERSION..=PROTOCOL_VERSION).contains(&version) {
                        return Err(std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            format!(
                                "version {} outside supported {}..={}",
                                version, MIN_PROTOCOL_VERSION, PROTOCOL_VERSION
                            ),
                        ));
                    }
                    self.state = DecodeState::Payload(len - 2);
                }
                DecodeState::Payload(len) => {
                    if src.len() < len {
                        return Ok(None);
                    }
                    let data = src.split_to(len);
                    let item: I = serde_json::from_slice(&data)
                        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
                    self.state = DecodeState::Header;
                    return Ok(Some(item));
                }
            }
        }
    }
}

/// Codec for the daemon side: reads [`Msg`], writes [`Cmd`].
pub type DaemonCodec = FrameCodec<Msg, Cmd>;

/// Codec for the worker side: reads [`Cmd`], writes [`Msg`].
pub type WorkerCodec = FrameCodec<Cmd, Msg>;

#[cfg(test)]
mod tests {
    use super::*;
    use bytes::BytesMut;
    use lixun_core::{Action, Category, DocId, Hit, RowMenuDef};

    fn sample_hit() -> Hit {
        Hit {
            id: DocId("doc-1".into()),
            category: Category::File,
            title: "title".into(),
            subtitle: "sub".into(),
            icon_name: None,
            kind_label: None,
            score: 1.5,
            action: Action::OpenUri {
                uri: "mid:abc".into(),
            },
            extract_fail: false,
            sender: None,
            recipients: None,
            body: Some("body".into()),
            secondary_action: None,
            source_instance: "semantic".into(),
            row_menu: RowMenuDef::empty(),
            mime: None,
        }
    }

    /// JSON-string equality is used instead of `PartialEq` because
    /// the wire payload includes types from `lixun-core` and
    /// `lixun-mutation` (e.g. `Hit`, `AnnHit`) that intentionally do
    /// not derive `PartialEq`. Stable JSON via `to_string` + parsed
    /// re-encode is sufficient to prove the round-trip is lossless.
    fn round_trip<T>(value: T)
    where
        T: Serialize + DeserializeOwned,
    {
        let s1 = serde_json::to_string(&value).expect("serialize");
        let back: T = serde_json::from_str(&s1).expect("deserialize");
        let s2 = serde_json::to_string(&back).expect("re-serialize");
        assert_eq!(s1, s2, "round-trip mismatch");
    }

    #[test]
    fn cmd_handshake_round_trip() {
        round_trip(Cmd::Handshake { proto_version: 1 });
    }

    #[test]
    fn cmd_embed_round_trip() {
        round_trip(Cmd::Embed {
            docs: vec![UpsertedDoc {
                doc_id: "d1".into(),
                source_instance: "fs".into(),
                mtime: 42,
                mime: Some("text/plain".into()),
                body: Some("hello".into()),
            }],
        });
    }

    #[test]
    fn cmd_delete_round_trip() {
        round_trip(Cmd::Delete {
            doc_id: "d1".into(),
        });
    }

    #[test]
    fn cmd_search_text_round_trip() {
        round_trip(Cmd::SearchText {
            req_id: 7,
            query: "foo".into(),
            k: 10,
        });
    }

    #[test]
    fn cmd_search_image_round_trip() {
        round_trip(Cmd::SearchImage {
            req_id: 8,
            query: "img".into(),
            k: 5,
        });
    }

    #[test]
    fn cmd_backfill_start_round_trip() {
        round_trip(Cmd::BackfillStart { req_id: 11 });
    }

    #[test]
    fn cmd_callback_reply_round_trip() {
        round_trip(Cmd::CallbackReply {
            req_id: 99,
            resp: CallbackResp::AllDocIds {
                ids: vec!["a".into(), "b".into()],
            },
        });
    }

    #[test]
    fn cmd_classify_query_round_trip() {
        round_trip(Cmd::ClassifyQuery {
            req_id: 9,
            query: "photos of dogs".into(),
        });
    }

    #[test]
    fn cmd_shutdown_round_trip() {
        round_trip(Cmd::Shutdown);
    }

    #[test]
    fn msg_handshake_ok_round_trip() {
        round_trip(Msg::HandshakeOk {
            proto_version: 1,
            worker_version: "0.5.0".into(),
        });
    }

    #[test]
    fn msg_search_result_round_trip() {
        round_trip(Msg::SearchResult {
            req_id: 7,
            hits: vec![AnnHit {
                doc_id: "d1".into(),
                distance: 0.25,
            }],
        });
    }

    #[test]
    fn msg_classify_result_round_trip() {
        round_trip(Msg::ClassifyResult {
            req_id: 9,
            modality: Modality::Both,
        });
    }

    #[test]
    fn msg_call_all_doc_ids_round_trip() {
        round_trip(Msg::CallAllDocIds { req_id: 1 });
    }

    #[test]
    fn msg_call_hydrate_doc_round_trip() {
        round_trip(Msg::CallHydrateDoc {
            req_id: 2,
            doc_id: "d1".into(),
        });
    }

    #[test]
    fn msg_call_get_body_round_trip() {
        round_trip(Msg::CallGetBody {
            req_id: 3,
            doc_id: "d1".into(),
        });
    }

    #[test]
    fn msg_backfill_complete_round_trip() {
        round_trip(Msg::BackfillComplete {
            req_id: 11,
            submitted: 100,
            total: 120,
        });
    }

    #[test]
    fn msg_error_round_trip() {
        round_trip(Msg::Error {
            req_id: 0,
            code: ErrorCode::Internal,
            detail: "boom".into(),
        });
    }

    #[test]
    fn callback_resp_all_variants_round_trip() {
        round_trip(CallbackResp::AllDocIds {
            ids: vec!["x".into()],
        });
        round_trip(CallbackResp::HydrateDoc {
            hit: Some(sample_hit()),
        });
        round_trip(CallbackResp::HydrateDoc { hit: None });
        round_trip(CallbackResp::GetBody {
            body: Some("body".into()),
        });
        round_trip(CallbackResp::GetBody { body: None });
        round_trip(CallbackResp::Error {
            code: ErrorCode::Storage,
            detail: "io".into(),
        });
    }

    #[test]
    fn error_code_all_variants_round_trip() {
        for code in [
            ErrorCode::BadRequest,
            ErrorCode::Internal,
            ErrorCode::Storage,
            ErrorCode::Callback,
            ErrorCode::Version,
        ] {
            round_trip(code);
        }
    }

    /// Two-codec duplex test: encode with one side's codec, decode
    /// with the other's, simulating the wire.
    #[test]
    fn duplex_codec_cmd_then_msg() {
        let mut daemon: DaemonCodec = FrameCodec::new();
        let mut worker: WorkerCodec = FrameCodec::new();

        let cmd = Cmd::SearchText {
            req_id: 42,
            query: "hello".into(),
            k: 3,
        };
        let cmd_json = serde_json::to_string(&cmd).unwrap();
        let mut buf = BytesMut::new();
        daemon.encode(cmd, &mut buf).expect("encode cmd");

        let decoded = worker.decode(&mut buf).expect("decode cmd").expect("frame");
        assert_eq!(serde_json::to_string(&decoded).unwrap(), cmd_json);
        assert!(buf.is_empty());

        let msg = Msg::SearchResult {
            req_id: 42,
            hits: vec![AnnHit {
                doc_id: "d1".into(),
                distance: 0.1,
            }],
        };
        let msg_json = serde_json::to_string(&msg).unwrap();
        let mut buf = BytesMut::new();
        worker.encode(msg, &mut buf).expect("encode msg");
        let decoded = daemon.decode(&mut buf).expect("decode msg").expect("frame");
        assert_eq!(serde_json::to_string(&decoded).unwrap(), msg_json);
        assert!(buf.is_empty());
    }

    /// Fragmented input: the decoder must hold state across partial
    /// reads and only emit a frame when all bytes have arrived.
    #[test]
    fn codec_handles_fragmented_input() {
        let mut daemon: DaemonCodec = FrameCodec::new();
        let mut worker: WorkerCodec = FrameCodec::new();

        let cmd = Cmd::Embed {
            docs: vec![UpsertedDoc {
                doc_id: "d1".into(),
                source_instance: "fs".into(),
                mtime: 1,
                mime: None,
                body: Some("x".repeat(200)),
            }],
        };
        let cmd_json = serde_json::to_string(&cmd).unwrap();
        let mut full = BytesMut::new();
        daemon.encode(cmd, &mut full).expect("encode");
        let full_vec: Vec<u8> = full.to_vec();

        let mut buf = BytesMut::new();
        for chunk in full_vec.chunks(7) {
            buf.extend_from_slice(chunk);
            match worker.decode(&mut buf).expect("decode") {
                Some(decoded) => {
                    assert_eq!(serde_json::to_string(&decoded).unwrap(), cmd_json);
                    assert!(buf.is_empty());
                    return;
                }
                None => continue,
            }
        }
        panic!("frame never decoded after feeding all bytes");
    }

    /// Reject frames whose declared version is below the minimum.
    #[test]
    fn codec_rejects_too_old_version() {
        if MIN_PROTOCOL_VERSION == 0 {
            return;
        }
        let mut buf = BytesMut::new();
        buf.put_u32(2);
        buf.put_u16(MIN_PROTOCOL_VERSION - 1);

        let mut codec: WorkerCodec = FrameCodec::new();
        let err = codec.decode(&mut buf).expect_err("must reject");
        assert_eq!(err.kind(), std::io::ErrorKind::InvalidData);
    }

    /// Reject a length prefix smaller than the version field.
    #[test]
    fn codec_rejects_truncated_length() {
        let mut buf = BytesMut::new();
        buf.put_u32(1);

        let mut codec: WorkerCodec = FrameCodec::new();
        let err = codec.decode(&mut buf).expect_err("must reject");
        assert_eq!(err.kind(), std::io::ErrorKind::InvalidData);
    }
}
