[package]
name = "lixun-preview-folder"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lixun-core = { path = "../lixun-core" }
lixun-preview = { path = "../lixun-preview" }
anyhow.workspace = true
inventory.workspace = true
tracing.workspace = true
gtk.workspace = true

[lib]
name = "lixun_preview_folder"
path = "src/lib.rs"
